⛏️ Split debt and redemption fees
WallfacerLabs/trinity-sc pull request #5
Opened 2024-04-23 11:53 UTC by nezouse

2024-04-24 10:25 UTC, MiksuJak requested changes
Lacks a test, that protocol fees are transferred to distributor address

2024-04-25 11:06 UTC, MiksuJak approved these changes

2024-04-29 11:35 UTC, MiksuJak commented
* **#5** <a href="https://app.graphite.dev/github/pr/WallfacerLabs/trinity-sc/5?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nezouse and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-29 13:49 UTC, Szymx95 commented on contracts/Dependencies/AddressesConfigurable.sol
> +		vesselManagerOperations = _addresses[14];
```suggestion
		gasPoolAddress = _addresses[7];
		priceFeed = _addresses[8];
		sortedVessels = _addresses[9];
		stabilityPool = _addresses[10];
		timelockAddress = _addresses[11];
		treasuryAddress = _addresses[12];
		vesselManager = _addresses[13];
		vesselManagerOperations = _addresses[14];
		distributorAddress = _addresses[6];
```
Why isn't distributor address added as last in the list ?

2024-04-29 13:56 UTC, Szymx95 approved these changes

2024-04-29 13:58 UTC, merged